[workspace.package]
edition = "2024"
authors = ["dwardy (dillon.ward.uk@gmail.com)"]

[workspace]
members = ["day1", "day10", "day11", "day12", "day2", "day3", "day4", "day5", "day6", "day7", "day8", "day9"]
resolver = "3"
